name: Generate ASCII Artwork

on:
  push

jobs: 
    ascii_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Intall cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay Program
          run: cowsay -f dragon "Run for cover, I am a dragon...RAWR" >> dragon.txt

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

        - name: Read File
          run: cat dragon.txt

        - name: List repo Files
          run: ls -ltra