name: Generate ASCII Artwork

on:
  push

jobs: 
   build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay prgram
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for the Cover...." >> dragon.txt

    - name: Upload drgon
      uses: actions/upload-artifact@v3
      with:
        name: dragon-file
        path: dragon.txt
     
   test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download dragon
      uses: actions/download-artifact@v3
      with:
        name: dragon-file

    - name: Test File
      run: grep -i "dragon" dragon.txt

   deploy_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps: 
      - name: Download dragon
        uses: actions/download-artifact@v3
        with:
          name: dragon-file
          
      - name:  read
        run: cat dragon.txt

      - name: deploy
        run: echo "Deploying...."

