name: Generate ASCII Artwork

on:
  push

jobs: 
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f frog "Run for the Cover.... I am a frog" >> frog.txt

      - name: Upload dragon
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dragon-file
          path: frog.txt
     
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon
        uses: actions/download-artifact@v4.3.0
        with:
          name: dragon-file

      - name: Test File
        run: grep -i "frog" frog.txt

  deploy_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps: 
      - name: Download dragon
        uses: actions/download-artifact@v4.3.0
        with:
          name: dragon-file

      - name: Read
        run: cat frog.txt

      - name: Deploy
        run: echo "Deploying...."
